language: generic
dist: bionic
sudo: false
addons:
  apt:
    packages:
      - libxkbcommon-x11-0
      - libosmesa6
      - libglx-mesa0
      - libopengl0
      - libglx0
      - libdbus-1-3
cache:
  apt: true
  pip: true
env:
    # TRAVIS_PYTHON_VERSION is only needed for neo's setup.py
    # OPENBLAS_NUM_THREADS=1 avoid slowdowns:
    # https://github.com/xianyi/OpenBLAS/issues/731
    global: PYTHON_VERSION=3.7 DISPLAY=:99.0 MNE_LOGGING_LEVEL=warning
            TRAVIS_PYTHON_VERSION=3.7 CONDA_VERSION=">=4.3.27"
            OPENBLAS_NUM_THREADS=1

matrix:
    include:
        # Linux
        - os: linux
          env: CONDA_ENV="environment.yml"
               PYTHON_VERSION=3.7


        # OSX conda
        - os: osx
          env: CONDA_ENV="environment.yml"
               PYTHON_VERSION=3.7


before_install:
  - if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1400x900x24 -ac +extension GLX +render -noreset;
    fi;
  - wget https://raw.githubusercontent.com/mne-tools/mne-python/master/environment.yml
  - git clone https://github.com/astropy/ci-helpers.git;
  - source ci-helpers/travis/setup_conda.sh;
  - conda activate base;
  - conda env update --file $CONDA_ENV;
  - pip install -U Cython
  - pip install -U mutar
  - pip install flake8 check-manifest pydocstyle
  - pip install codecov

install:
  - python setup.py build_ext --inplace
  - pip install -e .

script:
  # - export NUMBA_DISABLE_JIT=1
  - travis_wait 30 pytest -lv --cov-report term-missing groupmne --cov=groupmne --cov-config .coveragerc
  - make
  - flake8 --count groupmne
  - pydocstyle groupmne

after_success:
  - cp .coverage $TRAVIS_BUILD_DIR
  - codecov --root $TRAVIS_BUILD_DIR || echo "codecov upload failed"
