name: groupmne-env
channels:
- defaults

dependencies:
  - cython
  - flake8
  - h5py
  - joblib
  - jupyter
  - matplotlib
  - mkl
  - numba
  - numexpr
  - numpy
  - numpy
  - numpydoc
  - pandas>=0.18
  - pillow
  - pip
  - psutil
  - pyface>=6
  - pyqt>=5.9
  - pytest
  - pytest-cov
  - pytest-mock
  - pytest-timeout
  - python<3.7
  - scikit-learn
  - scipy
  - statsmodels
  - testpath<0.4
  - traits>=4.6.0
  - traitsui>=6
  - xlrd
  - pip:
    - mne
    - vtk
    - pyvista>=0.20.3
    - dipy --only-binary dipy
    - nibabel
    - nilearn
    - neo
    - pytest-faulthandler
    - pytest-sugar
    - pydocstyle
    - codespell
    - python-picard
    - pylsl>=1.12
    - panel
    - mutar
